---
title: 'No lake is an island: PhD Opportunity'
tags:
  - environmetrics
  - limnology
  - R
  - UKLEON
category: Science
excerpt: '[NERC](http://www.nerc.ac.uk ''NERC Website'') recently funded the formation
  of the UK Lake Ecological Observatory Network (UKLEON) as part of the its [Networks
  of Sensors](http://www.nerc.ac.uk/research/programmes/nos/ ''NERC Networks of Sensors
  home page'') programme. UKLEON is led by [Ian Jones](http://www.ceh.ac.uk/staffwebpages/IanJones.html
  ''Ian Jones&#8217; staff page'') at [CEH](http://www.ceh.ac.uk ''CEH Website'')
  [Lancaster](http://www.ceh.ac.uk/sites/lancaster.html ''CEH Lancaster''). A fully-funded
  PhD project is associated with the UKLEON project, with the aim of investigating
  high resolution coherence in lake dynamics.'
date: 2011-06-14 12:00:00
description: >-
  The successful student will be based at CEH Lancaster but registered for a PhD in the
  Department of Geography at UCL, receiving co-supervision via both institutions. The project
  would suit a computer literate and numerate student, with a background in
  limnology/ecology/environmental science and some statistical experience an advantage, but full
  training will be provided during the PhD. The closing date for applications is 29 July 2011.
  See the UCL advert for full details of the PhD project and the application procedure. If you
  are interested in the PhD you can contact me or the other supervisors for informal discussions
  about the project.
author: Gavin Simpson
categories:
  - Science
comments:
  giscus:
    repo: gavinsimpson/fromthebottomoftheheap-comments
    repo-id: R_kgDOUUVJuA
    category: Blog comments
    category-id: DIC_kwDOUUVJuM4DFRne
    mapping: pathname
    reactions-enabled: true
    input-position: top
    theme: preferred_color_scheme
    language: en
---

::: {.column-margin .post-taxonomy}
#### Posted in
[Science](/category/science/){.badge .text-bg-warning}

#### Tagged
[environmetrics](/tag/environmetrics/){.badge .text-bg-dark}
[limnology](/tag/limnology/){.badge .text-bg-dark}
[R](/tag/r/){.badge .text-bg-dark}
[UKLEON](/tag/ukleon/){.badge .text-bg-dark}
:::


[NERC](http://www.nerc.ac.uk 'NERC Website') recently funded the formation of the UK Lake Ecological Observatory Network (UKLEON) as part of the its [Networks of Sensors](http://www.nerc.ac.uk/research/programmes/nos/ 'NERC Networks of Sensors home page') programme. UKLEON is led by [Ian Jones](http://www.ceh.ac.uk/staffwebpages/IanJones.html 'Ian Jones&#8217; staff page') at [CEH](http://www.ceh.ac.uk 'CEH Website') [Lancaster](http://www.ceh.ac.uk/sites/lancaster.html 'CEH Lancaster'). A fully-funded PhD project is associated with the UKLEON project, with the aim of investigating high resolution coherence in lake dynamics.

The successful student will be based at CEH Lancaster but registered for a
PhD in the [Department of Geography](http://www.geog.ucl.ac.uk "UCL Department of Geography") at [UCL](http://www.ucl.ac.uk "UCL website"), receiving co-supervision via both institutions. The project would suit a computer literate and numerate student, with a background in limnology/ecology/environmental science and some statistical experience an advantage, but full training will be provided during the PhD. The closing date for applications is 29 July 2011. See the UCL [advert](http://ucfagls.files.wordpress.com/2011/06/ucl-lakesphdadvert.pdf) for full details of the PhD project and the application procedure. If you are interested in the PhD you can contact me or the other supervisors for informal discussions about the project.

::: {.post-navigation .d-flex .justify-content-between .gap-3}
<span>[← Older: Embedding a time series with time delay in R &mdash; Part II](/2011/06/14/embedding-a-time-series-with-time-delay-in-r-part-ii/)</span>
<span class="text-end">[Newer: Smoothing temporally correlated data →](/2011/07/21/smoothing-temporally-correlated-data/)</span>
:::
