---
title: ISEC 2016 Talk
tags:
  - Palaeoecology
  - Thresholds
  - R
  - Time series
  - Additive models
  - Location
  - Scale
  - GAMLSS
category: Science
date: 2016-07-02 12:00:00
description: >-
  My ISEC 2016 talk, Estimating temporal change in mean and variance of community composition via
  location, scale additive models, describes some of my recent research into methods to analyse
  palaeoenvironmental time series from sediment cores.
author: Gavin Simpson
categories:
  - Science
comments:
  giscus:
    repo: gavinsimpson/fromthebottomoftheheap-comments
    repo-id: R_kgDOUUVJuA
    category: Blog comments
    category-id: DIC_kwDOUUVJuM4DFRne
    mapping: pathname
    reactions-enabled: true
    input-position: top
    theme: preferred_color_scheme
    language: en
---

::: {.column-margin .post-taxonomy}
#### Posted in
[Science](/category/science/){.badge .text-bg-warning}

#### Tagged
[Palaeoecology](/tag/palaeoecology/){.badge .text-bg-dark}
[Thresholds](/tag/thresholds/){.badge .text-bg-dark}
[R](/tag/r/){.badge .text-bg-dark}
[Time series](/tag/time-series/){.badge .text-bg-dark}
[Additive models](/tag/additive-models/){.badge .text-bg-dark}
[Location](/tag/location/){.badge .text-bg-dark}
[Scale](/tag/scale/){.badge .text-bg-dark}
[GAMLSS](/tag/gamlss/){.badge .text-bg-dark}
:::

::: {.column-margin .post-links}
{{< include ../../../../includes/social-blogroll.qmd >}}
:::


My ISEC 2016 talk, *Estimating temporal change in mean and variance of community composition via location, scale additive models*, describes some of my recent research into methods to analyse palaeoenvironmental time series from sediment cores.

Using data from two varved lakes

* Lake 227, Experimental Lakes Area, Ontario, Canada, and
* Baldeggersee, Switzerland,

I use location scale generalised additive models to simultaneously model the mean (trend) and the variance of time series of fossil algal pigments and diatom counts.

These techniques may be applied to data from less ideal situations, where observations are irregularly sampled in time and have varying sample intervals/effects of time averaging.

The slide deck can be downloaded from
[Figshare](https://10.6084/m9.figshare.3470144.v1).

<div style="margin-left: auto; margin-right: auto; width: 700px; height: 716px;">
   <iframe src="https://widgets.figshare.com/articles/3470144/embed?show_title=1" width="700" height="716" frameborder="0"></iframe>
</div>

::: {.post-navigation .d-flex .justify-content-between .gap-3}
<span>[← Older: Rootograms](/2016/06/07/rootograms/)</span>
<span class="text-end">[Newer: Simultaneous intervals for smooths revisited →](/2016/12/15/simultaneous-interval-revisited/)</span>
:::
