project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - blog/index.qmd
    - feed-R/index.qmd
    - 404.qmd
    - about/index.qmd
    - permissions/index.qmd
    - publications/**/*.qmd
    - research/index.qmd
    - lab/**/*.qmd
    - teaching/**/*.qmd
    - workshops/**/*.qmd
    - slides/index.qmd
    - code/**/*.qmd
    - "20*/**/index.qmd"
    - category/**/*.qmd
    - tag/**/*.qmd
  resources:
    - assets/**
    - slides/**
    - teaching/**
    - workshops/**
    - code/**/*.R
    - code/**/*.r
    - code/**/*.zip
    - ads.txt
    - robots.txt
    - googlec511babfa558a9c1.html

website:
  title: From the bottom of the heap
  description: "My website and blog: research on lakes, past and present"
  site-url: https://fromthebottomoftheheap.net
  favicon: assets/ico/favicon.svg
  navbar:
    pinned: true
    background: light
    left:
      - text: Home
        icon: house-door
        href: /index.qmd
      - text: About
        icon: info-circle
        href: /about/index.qmd
      - text: Blog
        icon: chat-left-text
        href: /blog/index.qmd
      - text: Publications
        icon: file-earmark-text
        href: /publications/index.qmd
      - text: Research
        icon: tools
        href: /research/index.qmd
      - text: The Lab
        icon: funnel
        menu:
          - text: About
            href: /lab/index.qmd
          - text: Research
            href: /lab/research/index.qmd
          - text: Members
            href: /lab/members/index.qmd
          - text: Publications
            href: /lab/publications/index.qmd
          - text: Join the lab
            href: /lab/join/index.qmd
      - text: Resources
        icon: collection
        menu:
          - text: Teaching
            href: /teaching/index.qmd
          - text: Workshops
            href: /workshops/
          - text: Slides
            href: /slides/index.qmd
      - text: Code
        icon: code-slash
        menu:
          - text: DPER Scripts
            href: /code/dper-scripts/index.qmd
          - text: R Packages
            href: /code/r-packages/index.qmd
    right:
      - icon: github
        href: https://github.com/gavinsimpson
        aria-label: GitHub
      - icon: rss
        href: /feed.xml
        aria-label: RSS feed
  page-footer:
    left: "Copyright © 2010–2026 Gavin Simpson"
    center: "Content available under a [Creative Commons Attribution 4.0 licence](/permissions/)."
    right:
      - icon: github
        href: https://github.com/gavinsimpson
      - icon: envelope
        href: mailto:ucfagls@gmail.com
      - text: ORCID
        href: https://orcid.org/0000-0002-9084-8413
  open-graph: true
  twitter-card:
    creator: "@ucfagls"
    site: "@ucfagls"

bibliography: _biblio/blog-biblio.bib
csl: _biblio/frontiers.csl

format:
  html:
    theme: [default, theme.scss]
    toc: false
    code-overflow: scroll
    include-in-header: includes/in-header.html
    anchor-sections: false
    link-external-newwindow: false

lang: en
