[build]
  publish = "_site"
  command = ""

[[redirects]]
  from = "/2011/10/21/228/"
  to = "/2011/10/21/generating-sets-of-permutations/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.fromthebottomoftheheap.net/*"
  to = "https://fromthebottomoftheheap.net/:splat"
  status = 301
  force = true
