---
title: Summer hiatus
tags:
  - work
category: Science
date: 2018-10-15 13:00:00
excerpt_separator: <!--more-->
excerpt: <!--more-->
description: >-
  It's been quite some time since I last posted anything here. Mostly this was due to a very busy
  schedule since May that included teaching an online stats course, attending & presenting at
  three conferences, giving workshops at two of those conferences, and taking some well-earned
  vacation in Europe. Summer was also a busy time for manuscripts moving through the pipeline to
  being accepted and published. One thing I had hoped to do with the blog this year was publicize
  some of the work I do a little more. So, as normal service resumes here I hope to post some
  short pieces highlighting new papers that came out over the summer, and a few of these will be
  coming out over the next week or two.
author: Gavin Simpson
categories:
  - Science
comments:
  giscus:
    repo: gavinsimpson/fromthebottomoftheheap-comments
    repo-id: R_kgDOUUVJuA
    category: Blog comments
    category-id: DIC_kwDOUUVJuM4DFRne
    mapping: pathname
    reactions-enabled: true
    input-position: top
    theme: preferred_color_scheme
    language: en
---

::: {.column-margin .post-taxonomy}
#### Posted in
[Science](/category/science/){.badge .text-bg-warning}

#### Tagged
[work](/tag/work/){.badge .text-bg-dark}
:::


It's been quite some time since I last posted anything here. Mostly this was due to a very busy schedule since May that included teaching an online stats course, attending & presenting at three conferences, giving workshops at two of those conferences, and taking some well-earned vacation in Europe. Summer was also a busy time for manuscripts moving through the pipeline to being accepted and published. One thing I had hoped to do with the blog this year was publicize some of the work I do a little more. So, as normal service resumes here I hope to post some short pieces highlighting new papers that came out over the summer, and a few of these will be coming out over the next week or two. 

One of the reasons for having this blog in the first place was to get me back into "writing mode"; I find it difficult at times, especially when the to-do list is long, to force myself to carve out time to both think *and* write. And as I get more and more out of practice writing, it takes more and more time to start or pick up work on manuscripts describing new results, and the words don't flow easily at all. I find it much easier to write when I am towards the end of a writing period because I've literally forced myself to write. And, whilst blog posts aren't the same kind of writing as for manuscripts, I hope that by just doing a little writing each week, it'll be that bit easier to pick up work on a languishing manuscript or start something new.

Let's see how I get on...

<!--more-->

::: {.post-navigation .d-flex .justify-content-between .gap-3}
<span>[← Older: Fitting GAMs with brms: part 1](/2018/04/21/fitting-gams-with-brms/)</span>
<span class="text-end">[Newer: Controls on subannual variation in pCO<sub>2</sub> in productive hardwater lakes →](/2018/10/15/wiik-jgr-co2-paper/)</span>
:::
