---
title: At the frontiers of palaeoecology
tags:
  - Palaeoecology
  - Presentations
  - R
  - Time series
category: Science
date: 2015-03-31 12:00:00
description: >-
  A couple of weeks ago, I had the pleasure of attending and participating in a symposium held to
  honour John Birks as he retires from the University of Bergen and becomes Professor Emeritus.
  The symposium, titled "At the Frontiers of Palaeoecology", took place on 19--20th March in
  Bergen, Norway, and was a wonderful mix of colleagues old and new discussing John's
  contributions to the field of palaeoecology and their collaborations with him. Alongside this
  reminiscing were several presentations describing new areas of research by colleagues and
  collaborators of John.
author: Gavin Simpson
categories:
  - Science
comments:
  giscus:
    repo: gavinsimpson/fromthebottomoftheheap-comments
    repo-id: R_kgDOUUVJuA
    category: Blog comments
    category-id: DIC_kwDOUUVJuM4DFRne
    mapping: pathname
    reactions-enabled: true
    input-position: top
    theme: preferred_color_scheme
    language: en
---

::: {.column-margin .post-taxonomy}
#### Posted in
[Science](/category/science/){.badge .text-bg-warning}

#### Tagged
[Palaeoecology](/tag/palaeoecology/){.badge .text-bg-dark}
[Presentations](/tag/presentations/){.badge .text-bg-dark}
[R](/tag/r/){.badge .text-bg-dark}
[Time series](/tag/time-series/){.badge .text-bg-dark}
:::

::: {.column-margin .post-links}
{{< include ../../../../includes/social-blogroll.qmd >}}
:::


A couple of weeks ago, I had the pleasure of attending and 
participating in a symposium held to honour John Birks as he retires 
from the University of Bergen and becomes Professor Emeritus. The 
symposium, titled "At the Frontiers of Palaeoecology", took place on 
19--20th March in Bergen, Norway, and was a wonderful mix of colleagues 
old and new discussing John's contributions to the field of 
palaeoecology and their collaborations with him. Alongside this 
reminiscing were several presentations describing new areas of research 
by colleagues and collaborators of John.

I gave a talk on the first day, which was of the latter type. I made 
the case for the wider use among palaeoecologists of modern statistical 
methods that allow us to handle palaeoecological data as time series. 
For the most part, limited consideration has been given to the temporal 
aspects of stratigraphic data, principally because classical time 
series methods assume equally spaced observations and our dating 
methods come with considerable errors attached.

The slides from my presentation are available via 
[Figshare](http://doi.org/10.6084/m9.figshare.1354040).

<div style="margin-left: auto; margin-right: auto; width: 700px; height: 601px;">
   <iframe src="https://wl.figshare.com/articles/1354040/embed?show_title=1" frameborder="0" width="700" height="601"></iframe>
</div>

::: {.post-navigation .d-flex .justify-content-between .gap-3}
<span>[← Older: Harvesting Canadian climate data](/2015/01/14/harvesting-canadian-climate-data/)</span>
<span class="text-end">[Newer: Drawing rarefaction curves with custom colours →](/2015/04/16/drawing-rarefaction-curves-with-custom-colours/)</span>
:::
