---
title: AGU Fall Meeting 2015
tags:
  - Palaeoecology
  - Thresholds
  - R
  - Time series
  - Additive models
  - Wavelets
category: science
description: My poster, Rapid ecological change in lake ecosystems (GC13G-1236) in
  the Sedimentary records of threshold change (GC13G Moscone South Poster Hall 1340--1800,
  monday 14th December) describes some of my recent research into methods to analyse
  palaeoenvironmental time series from …
date: 2015-12-14 12:00:00
author: Gavin Simpson
categories:
  - science
comments:
  giscus:
    repo: gavinsimpson/fromthebottomoftheheap-comments
    category: Blog comments
    mapping: pathname
    reactions-enabled: true
    input-position: top
    theme: preferred_color_scheme
    language: en
---

::: {.column-margin .post-taxonomy}
#### Posted in
[science](/category/science/){.badge .text-bg-warning}

#### Tagged
[Palaeoecology](/tag/palaeoecology/){.badge .text-bg-dark}
[Thresholds](/tag/thresholds/){.badge .text-bg-dark}
[R](/tag/r/){.badge .text-bg-dark}
[Time series](/tag/time-series/){.badge .text-bg-dark}
[Additive models](/tag/additive-models/){.badge .text-bg-dark}
[Wavelets](/tag/wavelets/){.badge .text-bg-dark}
:::


My poster, *Rapid ecological change in lake ecosystems* (GC13G-1236) in the *Sedimentary records of threshold change* (GC13G Moscone South Poster Hall 1340--1800, monday 14th December) describes some of my recent research into methods to analyse palaeoenvironmental time series from sediment cores. Using data from a varved lake, Baldeggersee, Switzerland, I use location scale generalised additive models to simultaneously model the mean (trend) and the variance of a time series of diatom counts. Wavelets were used to investigate further variation in species dynamics during the well-documented history of eutrophication at the lake.

Both of these techniques may be applied to data from less ideal situations, where observations are irregularly sampled in time and have varying sample intervals/effects of time averaging. 

A PDF of my poster can be downloaded from
[Figshare](https://doi.org/10.6084/m9.figshare.2008245).

<div style="margin-left: auto; margin-right: auto; width: 700px; height: 601px;">
   <iframe src="https://widgets.figshare.com/articles/2008245/embed?show_title=1" frameborder="0" width="700" height="601"></iframe>
</div>

::: {.post-navigation .d-flex .justify-content-between .gap-3}
<span>[← Older: Are some seasons warming more than others?](/2015/11/23/are-some-seasons-warming-more-than-others/)</span>
<span class="text-end">[Newer: Better use of transfer functions? →](/2015/12/16/agu-transfer-functions/)</span>
:::
