all: visec-2020-simpson-bivariate-copula-gams.html website

visec-2020-simpson-bivariate-copula-gams.html: visec-2020-simpson-bivariate-copula-gams.Rmd my.css
	Rscript -e 'library("rmarkdown"); render("visec-2020-simpson-bivariate-copula-gams.Rmd")'
