---
title: analogue 0.14-0 released
tags:
  - Palaeoecology
  - Principal curves
  - R
  - analogue
category: R
date: 2014-10-14 12:00:00
description: >-
  A couple of week's ago I packaged up a new release of analogue, which is available from CRAN.
  Version 0.14-0 is a smaller update than the changes released in 0.12-0 and sees a continuation
  of the changes to dependencies to have packages in Imports rather than Depends. The main
  development of analogue now takes place on github and bugs and feature requests should be
  posted there. The Travis continuous integration system is used to automatically check the
  package as new code is checked in. There are several new functions and methods and a few bug
  fixes, the details of which are given below.
author: Gavin Simpson
categories:
  - R
comments:
  giscus:
    repo: gavinsimpson/fromthebottomoftheheap-comments
    repo-id: R_kgDOUUVJuA
    category: Blog comments
    category-id: DIC_kwDOUUVJuM4DFRne
    mapping: pathname
    reactions-enabled: true
    input-position: top
    theme: preferred_color_scheme
    language: en
---

::: {.column-margin .post-taxonomy}
#### Posted in
[R](/category/r/){.badge .text-bg-warning}

#### Tagged
[Palaeoecology](/tag/palaeoecology/){.badge .text-bg-dark}
[Principal curves](/tag/principal-curves/){.badge .text-bg-dark}
[R](/tag/r/){.badge .text-bg-dark}
[analogue](/tag/analogue/){.badge .text-bg-dark}
:::


A couple of week's ago I packaged up a new release of **analogue**, which is available from [CRAN](http://cran.r-project.org/web/packages/analogue/index.html). Version 0.14-0 is a smaller update than the changes released in 0.12-0 and sees a continuation of the changes to dependencies to have packages in Imports rather than Depends. The main development of **analogue** now takes place on [github](https://github.com/gavinsimpson/analogue/) and bugs and feature requests should be posted there. The Travis continuous integration system is used to automatically check the package as new code is checked in. There are several new functions and methods and a few bug fixes, the details of which are given below.

The main user-visible change over 0.12-0 is the **deprecation** of the `plot3d.prcurve()` method. The functionality is now in new function `Plot3d()` and `plot3d.prcurve()` is deprecated and if called needs to use the full function name. This change is to make analogue easier to install on MacOS X as now **rgl** is not needed to install **analogue**. If you want to plot the principal curve in an interactive 3d view, you'll need to get **rgl** installed first.

## New features

 * `n2()` is a new utility function to calculate Hill's N2 for sites (sample) & species (variables).
 
 * `optima()` can now compute bootstrap WA optima and uncertainty.

 * `performance()` has a new method for objects of class`"crossval"`.

 * `timetrack()` had several improvements including a new `predict()` method, which allows further points to be added to an 
   existing timetrack, a `points()` method to allow the addition of data to an existing timetrack plot, and the `plot()` method can create a blank plotting region allowing greater customisation.

 * `prcurve()` gets `predict()` and `fitted()` methods to predict locations of new samples on the principal curve and
   extract the locations of the training samples respectively.

 * `evenSample` is a utility function to look at the evenness of the distribution of samples along a gradient.

 * Data sets `Pollen`, `Biome`, `Climate`, and `Location` from the North American Modern Pollen Database have been updated to 
   version 1.7.3.

## Bug fixes

 * The calculation of AUC in `roc()` wasn't working correctly in some circumstances with just a couple of groups.

 * `crossval.pcr()` had a number of bugs in the k-fold CV routine which were leading to errors and the function not working.

     The progress bar was not being updated correctly either.

 * `predict.pcr()` was setting argument `ncomp` incorrectly if not supplied by the user.

 * `ChiSquare()` wasn't returning the transformation parameters required to transform leave-out data during crossvalidation or new samples for which predictions were required.

 * `plot3d.prcurve()` was not using the data and ordination components of the returned object. Note this function is now deprecated.

 * `predict.pcr()` was incorrectly calling the internal function `fitPCR` with the `:::` operator.

## Deprecated

 * `plot3d.prcurve()` is deprecated. Functionality is in new function `Plot3d()`. **Note**: in the next version of **analogue**, this functionality will be removed entirely and located in a new package [**analogueExtra**](https://github.com/gavinsimpson/analogueExtra).

::: {.post-navigation .d-flex .justify-content-between .gap-3}
<span>[← Older: Simulating species abundance data with coenocliner](/2014/07/31/simulating-species-abundance-data-with-the-coenocliner-package/)</span>
<span class="text-end">[Newer: Analysing a randomised complete block design with vegan →](/2014/11/03/randomized-complete-block-designs-and-vegan/)</span>
:::
